import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { NextPage } from 'next';
import Card from '../components/Card';
import { noteType } from '../types';
import Modal from '../components/Modal';
import { getAllNotes, getArchivedNotes } from '../services/notes';
import { FaArchive, FaPlus } from 'react-icons/fa';

const Home: NextPage = () => {
  const [archivedList, setArchivedList] = useState(false);
  const [archivedNotes, setArchivedNotes] = useState<noteType[]>([]);
  const [notes, setNotes] = useState<noteType[]>([]);
  const [showModal, setShowModal] = useState(false);
  const [count, setCount] = useState(0);

  
  const fetchData = async () => {
    const data = await getAllNotes();
    const data2 = await getArchivedNotes();
    setNotes(data);
    setArchivedNotes(data2);
  }
 
  useEffect(() => {
    fetchData();
  }, [count])

  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        />
      </Head>

      <main>
        <h1 className={styles.title}>
          {archivedList? 'Archived Notes' : 'My notes'}
        </h1>
        <ul className={styles.notesContainer}>
          <li>
            <div>
              <div className={styles.card}>
                <button onClick={() => setArchivedList(!archivedList)}>
                  <FaArchive/>
                </button>
              </div>
              {/* Button add */}
              {archivedList?null
              :<div className={styles.card}>
                <button onClick={() => setShowModal(true)}>
                  <FaPlus/>
                </button>
              </div>}
            </div>
          </li>
          {archivedList?
            (archivedNotes? archivedNotes.map((note)=>{
              return <li key={note.id}><Card note={note}
                setCount={setCount} 
                count={count}/></li>
            }): null)
          :
            (notes? notes.map((note)=>{
              return <li key={note.id}><Card note={note}
                setCount={setCount}
                count={count}/></li>
            }): null)
          }
        </ul>
        <Modal 
          showModal={showModal} 
          setShowModal={setShowModal} 
          setCount={setCount} 
          count={count}/>
      </main>
    </>
  );
};

export default Home;