import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { NextPage } from 'next';
import Card from '../components/Card';
import {noteType} from '../types';

const Home: NextPage = () => {
  const [archivedList, setArchivedList] = useState(false);
  const [notes, setNotes] = useState<noteType[]>([]);

  
  const fetchData = async () => {
    const res = await fetch('http://localhost:3001/notes');
    const data = await res.json();
    console.log(data);
    setNotes(data);
  }
 
  useEffect(() => {
    fetchData();
  }, [])

  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          {archivedList? 'Archived Notes' : 'Notes'}
        </h1>
        <button onClick={() => setArchivedList(!archivedList)}>
          {archivedList? 'go to notes' : 'go to archived notes'}
        </button>
        {archivedList? null : <button>add note</button>}
        {archivedList? null : <ul>
          {notes? notes.map((note)=>{
            return <li key={note.id}><Card note={note}/></li>
          }): "a"}
        </ul>}
      </main>
    </>
  );
};

export default Home;